# Generated by Django 4.1.3 on 2022-11-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_avertisement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avertisement',
            new_name='Advertisement',
        ),
    ]
