# Generated by Django 4.1.3 on 2022-11-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_advertisement_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image_description',
            field=models.CharField(default='foo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='product_description',
            field=models.CharField(default='foo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='slogan_text',
            field=models.CharField(default='foo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='style',
            field=models.CharField(default='foo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_audience',
            field=models.CharField(default='foo', max_length=500),
            preserve_default=False,
        ),
    ]
