# Generated by Django 4.1.3 on 2022-11-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_final_image_path_advertisement_processed_image_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='dalle_link',
            field=models.CharField(default='foo', max_length=750),
            preserve_default=False,
        ),
    ]
